controller_list:
  - name: gantry_crane/arm_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]

  # - name: gantry_crane/h_beam_controller
  #   action_ns: "follow_joint_trajectory"
  #   type: FollowJointTrajectory
  #   joints: [h_beam_joint_left]

  #   - name: gantry_crane/trolly_controller
  #   action_ns: "follow_joint_trajectory"
  #   type: FollowJointTrajectory
  #   joints: [trolly_joint]

  #   - name: gantry_crane/crane_controller
  #   action_ns: "follow_joint_trajectory"
  #   type: FollowJointTrajectory
  #   joints: [crane_joint]