controller_list:
  - name: fake_gantry_group_controller
    type: $(arg fake_execution_type)
    joints:
      - h_beam_joint_left
      - trolly_joint
      - crane_joint
  - name: fake_ur10_group_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
initial:  # Define initial robot poses.
  - group: ur10_group
    pose: transport_pose