position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - h_beam_joint_left
        - trolly_joint
        - crane_joint
    state_publish_rate: 50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
